#! /bin/bash

# for file in $1/*.thy; 
#     do echo $file;
#     ./ChasePerf "$file" >> wa_results.txt;
# done

while IFS= read -r line; do
  echo "$line"
  timeout 15 ./TPTPPerformanceLogger -i $line +RTS -K16M -RTS  --skolem-depth=4 --schedule=dfs --formula-type=cnf --tptp-path=./TPTP/
#  >> fc_results.txt
done
