#! /bin/bash

# for file in $1/*.thy; 
#     do echo $file;
#     ./ChasePerf "$file" >> wa_results.txt;
# done

while IFS= read -r line; do
  echo "$line"
  timeout 120 ./TPTPPerformanceLogger -i $line +RTS -K16M -RTS --schedule=rr --process-unit=5 --formula-type=cnf --tptp-path=/Programming/TPTP-v6.0.0/ >> chase_results.txt
done < "$1"
